name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the details below.
  - type: input
    id: package
    attributes:
      label: Package(s)
      description: Which package(s) are affected?
      placeholder: '@aristobyte-ui/button, @aristobyte-ui/utils'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: '2.x.x'
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide steps or a minimal reproduction.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Include relevant logs or screenshots (if any).
      render: shell
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: '20.17.0'
    validations:
      required: true
  - type: input
    id: package_manager
    attributes:
      label: Package manager
      placeholder: 'yarn / npm / pnpm / bun'
    validations:
      required: true
