name: Documentation Request
description: Report missing or unclear documentation
title: '[Docs]: '
labels: ['documentation']
body:
  - type: textarea
    id: issue
    attributes:
      label: What needs improvement?
      description: Describe the missing or unclear docs.
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Docs location
      placeholder: 'apps/docs/... or package README'
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested changes
